services:
  caddy:
    build:
      context: ./docker/caddy
    restart: unless-stopped
    ports:
      - "8001:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - ./:/srv
      - caddy_data:/data
      - caddy_config:/config

  php-fpm:
    image: php:8.3-fpm-alpine
    volumes:
      - ./:/srv

volumes:
  caddy_data:
  caddy_config:
